config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get 'welcome/index'

  resources :posts

  root 'posts#index'

  resources :posts do
    resources :comments
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :commenter, presence: true
  validates :body,      presence: true
  validates :post_id,   presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth, _signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    return user if user.present?
    registered_user = User.where(email: auth.info.email).first
    return registered_user if registered_user.present?
    User.create(name: auth.extra.raw_info.name, provider: auth.provider,
                uid: auth.uid, email: auth.info.email,
                password: Devise.friendly_token[0, 20])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController  < InheritedResources::Base
  belongs_to :post
  before_action :authenticate_user!
  # after_action :mail_interesed, only: :create
  def create
    create! { post_path(@post) }
  end

  def destroy
    destroy! { post_path(@post) }
  end

  def mail_interesed
    MailWorker.perform_async(@post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_action :authenticate_user!
  def create
    create!
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%= panel_row column_class: 'col-sm-4' do %>
  <%= panel title: comment.commenter, context: :info do %>
    <div class='panel-body'><%= comment.body %></div>
  <% end %>
    <%= nav as: :pills do %>
    <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
 <p> 
  <%= f.hidden_field :commenter, value: current_user.email %>
  </p>
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="navbar navbar-default navbar-static-top" role="navegacion">
    <div class="container">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".nav-top">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse nav-top">
        <ul class="nav navbar-nav navbar-left">
          <li> <%= link_to 'Home', root_path %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Edit User", edit_user_registration_path %> </li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
          <% else %>
            <li> <%= link_to 'Log in', new_user_session_path %> </li>
            <li> <%= link_to 'Registration', new_user_registration_path %>  </li>
            <li> <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %> </li>
            

          <% end %>
        </ul>
      </div>
    </div>
  </div>
    <% if notice!= nil %>
      <% if !notice.empty?%>
      <div class="alert alert-info" role="alert">
        <p class="notice">
         <%= notice %>
        </p>
      </div>
      <% end %>
    <% end %>

    <% if alert != nil %>
      <% if !alert.empty? %>
       <div class="alert alert-danger" role="alert">
      <p class="alert">
        <%= alert %>
      </p>
      </div>
      <% end %>    
    <% end %>
    <%= yield %>
        
  <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
  </div>
  </body>



</html>

app/views/posts/_form.html.erb
<%= form_for @post , layout: :basic do |f| %>
  <p>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star"></span> <%= link_to 'New post', new_post_path %>
</button>
<p/>
  <% @posts.each do |post| %>
    <%= panel_row column_class: 'col-sm-4' do %>
      <%= panel title: post.title, context: :info do %>
        <div class='panel-body'><%= post.text %></div>
      <% end %>
    
    <div class="dropdown">
      <button class="btn btn-default btn-lg dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
      Actions
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to 'Show', post %></a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to 'Edit', edit_post_path(post) %></a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></a></li>

      </ul>
    </div>
    <% end %>
  <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= panel_row column_class: 'col-sm-4' do %>
  <%= panel title: @post.title, context: :info do %>
    <div class='panel-body'><%= @post.text %></div>
  <% end %>
<% end %>

<h2>Comments</h2>
<%= render @post.comments %>
 
 <div>
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 </div>
<%= link_to 'Edit Post', edit_post_path(@post) %> |

<%= link_to 'Back to Posts', posts_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", controller: "posts" %>